import type { NextPage } from 'next'
import Head from 'next/head'
import HeroesList from './HeroesList/HeroesList'
import styles from '../styles/Home.module.css'
import { getHeroes } from './api/heroes'

const Home: NextPage = ({ heroes }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroesList heroes={heroes} />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      heroes: getHeroes()
    }
  }
}

export default Home
